### ISSUE TITLE
Fabric Session Error Reporting Improvements

### ISSUE THREAD

**Issue by michaelquigley** [openziti/fabric#19]
Session failures often result in "second order" error messages, where a subsystem (`xgress`, for example) produces an error message, which is bubbled up to the caller. In some cases, these messages are swallowed, resulting in something generic, like `EOF`.

Revisit session setup error paths and endeavor to produce generally better, clearer error messages about why session setup may have failed.

**Comment by plorenz** [comment]
There have been a lot of improvements in providing better visibility into why circuit setup has failed (see circuit events)
