### ISSUE TITLE
Metrics Watchdog

### ISSUE THREAD

**Issue by michaelquigley** [openziti/fabric#195]
Implement a metrics watchdog that can be hosted in either the controller or the router, which watches metrics values, and can be configured to execute:

* built-in handlers for `pprof-*`, `stack`, etc.
* external scripts

**Comment by plorenz** [comment]
Replaced with a backlog entry on the perf/stability project: https://github.com/orgs/openziti/projects/15/views/1?pane=issue&itemId=44641156
