### ISSUE TITLE
Split Link Connections Support Multiple Transport Protocols

### ISSUE THREAD

**Issue by michaelquigley** [openziti/fabric#222]
The split link functionality introduced with the `dilithium`-like flow control should ideally support multiple `transport` protocols. In Transwarp scenarios, it adds complexity to debugging and operating to run the ACK channel over `westworld3` in addition to the data channel.

We should support a mechanism to specify an alternate protocol for the ACK channel.

**Comment by michaelquigley** [comment]
This is potentially complicated by needing to support multiple listeners. Supporting multiple dialers is fairly trivial, but the listeners add complexity.

Intermediate solution is to support configuration to disable split link configuration.

**Comment by plorenz** [comment]
Closing as not planned for now. May reopen in ziti project later. It's likely we'll support some version of this as we implement UDP links
