### ISSUE TITLE
Enable docs endpoint for fabric REST API 

### ISSUE THREAD

**Issue by plorenz** [openziti/fabric#511]
The edge apis have a nice doc interface exposed at ./docs and/or swagger.json, but the fabric API isn't covered. 

/fabric/v1/docs does go to something, but it goes to something which only covers edge APIs

**Comment by avinilcode** [comment]
@plorenz I want to contribute, can you please assign this to me?

**Comment by plorenz** [comment]
Hi @avinilcode, I appreciate it! 

The edge is exposing its REST API in this code here: https://github.com/openziti/edge/blob/v0.24.2/controller/server/management-api.go#L113

We probably need something similar in this class: https://github.com/openziti/fabric/blob/v0.21.1/controller/api_impl/management-api.go

I haven't dug into why the edge API seems to be overriding the fabric doc, but there may be some other things that need to be done.

**Comment by avinilcode** [comment]
Ok, I will start working on it

**Comment by plorenz** [comment]
Hey @avinilcode, I'm going to unassign this. I see you've got another issue on the ziti project you're also working on. If someone picks this up, I'll ping you to see if you've got some work to share before hand.

**Comment by plorenz** [comment]
This will likely be fixed when we consolidate fabric and edge apis into a single API, along with moving to OpenAPI 3
