### ISSUE TITLE
Add cluster events

### ISSUE THREAD

**Issue by plorenz** [openziti/fabric#584]
Add events for things like:

* Peer connected 
    * Peer Id
    * Peer Address
    * Peer Version
* Peer disconnected
    * Peer Id
    * Peer Address
    * Peer Version
* Peer Added to configuration 
    * Peer Id
    * Peer Address  
* Peer Removed from configuration 
    * Peer Id
    * Peer Address   

Peer added/removed should only happen on leader, peer connect/disconnect should happen on all nodes

* Leadership gained
* Leadership lost 
* Entered read-only mode (not all nodes in cluster at same version)
* Exited read-only mode (all nodes in cluster at same version)

Do we need any other info (candidacy, ballots, etc)? There's more detail in the raft logs.

**Comment by mguthrie88** [comment]
How are we emitting or propagating errors or failures from Raft?

**Comment by plorenz** [comment]
Currently they're in the raft log. The raft log is being merged into the ziti log, but I'm working on making that configurable, so that it can be combined or go to a separate file.

**Comment by mguthrie88** [comment]
In that case I think this is a good starting place to launch from, nothing else obvious comes to mind
