### ISSUE TITLE
Health Check API

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/fabric#59]
Mike Guthrie was asking how to check the health of a Ziti Controller. The current strategy is to watch for open ports on the controller (REST API, Management, Control), but that doesn't mean things are working properly. He asked for a holistic endpoint to check that can report on the health of the controller.

We need to discuss what this means and how to allow the Edge to report it's status as well.

**Comment by mguthrie88** [comment]
The critical item for this is just that it returns an HTTP response code of 200 for healthy. Some apps will bake in additional diagnostic info as JSON into an endpoint like this, but that's at your discretion.

**Comment by plorenz** [comment]
Completed. Health check api available as part of xweb.
