### ISSUE TITLE
Mesh Building Race

### ISSUE THREAD

**Issue by michaelquigley** [openziti/fabric#7]
Assume a network configured like this:

```
001 -> 002 <- 003
```

…where router `002` advertises a listener, but routers `001` and `003` do not.

If both router `001` and `003` connect to the controller at the same time, before either router has an established link with `002`, the controller will end up creating redundant links. This scenario should end up creating a mesh with 2 links, but this race condition can result in an extra link for both hops.

This is ultimately because the connection handling code, which reevaluates the mesh and sends the appropriate `Link` commands across the control plane is not aware of the pending links of the other connection.

In practice, this is generally harmless as the redundant links don’t actually impact the performance of anything. This is generally an administrative hygiene issue.

## Potential Fixes

This could be fixed by adding pending link tracking support to the controller. When the controller issues a `Link` command to a router, the pending link is tracked. The list of pending links is considered along with the established links when evaluating the mesh.

Alternately, the controller could reap redundant links in a similar manner to how Failed links are reaped.

**Comment by plorenz** [comment]
Fixed. Redundant links requests are now handled by the router.
