### ISSUE TITLE
ampq event shipper should not crash the controller

### ISSUE THREAD

**Issue by mguthrie88** [openziti/fabric#732]
The ampq shipper is a great addition to allow event streaming to external systems, but it really needs the following two improvements to be viable in a production setting. 

1. Connection failure upon startup should not prevent the controller from starting, it should log an error and then continue
2. Failure to ship events should result in the data being buffered up to a configurable size while the connection retries, but if the buffer fills up the event shipping should log errors that it can't buffer anymore. 

Key idea - Metrics and event shipping should never crash the controller, and needs to be able to handle slow shipping, connection failures, auth errors, timeouts, etc.

**Comment by camotts** [comment]
Fixed by https://github.com/openziti/ziti/pull/1136 in ziti release 0.28.1
