### ISSUE TITLE
Resynchronize Mesh on Reconnect

### ISSUE THREAD

**Issue by michaelquigley** [openziti/fabric#8]
In a cold controller restart, the controller doesn’t know what links may have already been extant on the mesh. It will recreate a new mesh, and the existing links will eventually go stale. This doesn’t technically _hurt_ anything, but it is wasteful.

A second iteration of reconnect behavior would either persistently store the mesh state in the database, and then query connecting routers for their link tables (and possibly forwarding tables, eventually). It may also be useful to query the routers' link tables to rebuild the controller's internal representation.

**Comment by plorenz** [comment]
Fixed. Routers now inform controllers of their existing links on reconnect.
