### ISSUE TITLE
Migrate 'ziti-fabric' into Modularized 'ziti'

### ISSUE THREAD

**Issue by michaelquigley** [openziti/fabric#9]
Modularize the `ziti` CLI, such that the `ziti-fabric` components, the `ziti-edge` components, and any other interested parties can contribute CLI commands. Use careful namespacing: `ziti fabric`, `ziti edge`, etc. to ensure that there aren't overlaps.

Migrate `ziti-fabric` to use this new, modular `ziti` infrastructure.

**Comment by plorenz** [comment]
Fixed. ziti cmd now incorporates and replaces ziti-fabric and ziti-edge
